version: '3'

services:
  dbpostgres:
    build: .
    container_name: dbpostgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=youtube_spring_auth
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-pgadmin-network
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 15432:80
    depends_on:
      - dbpostgres
    networks:
      - postgres-pgadmin-network

networks: 
  postgres-pgadmin-network:
    driver: bridge

volumes:
  pgdata: {}